// Keep the original device-font choices, including the existing rounded default.
export const fonts = {
  rounded: '"Arial Rounded MT Bold", "SF Pro Rounded", Arial, "PingFang SC", sans-serif',
  sans: 'Arial, "Helvetica Neue", "PingFang SC", sans-serif',
  condensed: 'Impact, "Arial Narrow", "PingFang SC", sans-serif',
  serif: 'Georgia, "Times New Roman", "Songti SC", serif',
  helveticaNeue: '"Helvetica Neue", sans-serif',
  avenirNext: '"Avenir Next", sans-serif',
  avenir: '"Avenir", sans-serif',
  futura: '"Futura", sans-serif',
  gillSans: '"Gill Sans", sans-serif',
  optima: '"Optima", sans-serif',
  palatino: '"Palatino", sans-serif',
  baskerville: '"Baskerville", sans-serif',
  hoeflerText: '"Hoefler Text", sans-serif',
  timesNewRoman: '"Times New Roman", sans-serif',
  verdana: '"Verdana", sans-serif',
  tahoma: '"Tahoma", sans-serif',
  trebuchet: '"Trebuchet MS", sans-serif',
  segoeUI: '"Segoe UI", sans-serif',
  aptos: '"Aptos", sans-serif',
  calibri: '"Calibri", sans-serif',
  cambria: '"Cambria", sans-serif',
  candara: '"Candara", sans-serif',
  consolas: '"Consolas", sans-serif',
  menlo: '"Menlo", sans-serif',
  courierNew: '"Courier New", sans-serif',
  roboto: '"Roboto", sans-serif',
  droidSans: '"Droid Sans", sans-serif',
  ubuntu: '"Ubuntu", sans-serif',
  dejavuSans: '"DejaVu Sans", sans-serif',
  liberationSans: '"Liberation Sans", sans-serif',
  pingFangSC: '"PingFang SC", sans-serif',
  pingFangTC: '"PingFang TC", sans-serif',
  hiraginoSans: '"Hiragino Sans", sans-serif',
  hiraginoMincho: '"Hiragino Mincho ProN", sans-serif',
  songtiSC: '"Songti SC", sans-serif',
  heitiSC: '"Heiti SC", sans-serif',
  microsoftYaHei: '"Microsoft YaHei", sans-serif',
  microsoftJhengHei: '"Microsoft JhengHei", sans-serif',
  simSun: '"SimSun", sans-serif',
  simHei: '"SimHei", sans-serif',
  yuGothic: '"Yu Gothic", sans-serif',
  yuMincho: '"Yu Mincho", sans-serif',
  meiryo: '"Meiryo", sans-serif',
  malgunGothic: '"Malgun Gothic", sans-serif',
  appleSDGothicNeo: '"Apple SD Gothic Neo", sans-serif',
  batang: '"Batang", sans-serif',
  nunito: '"Nunito Variable", sans-serif',
  inter: '"Inter Variable", sans-serif',
  robotoCondensed: '"Roboto Condensed Variable", sans-serif',
  notoSerif: '"Noto Serif Variable", serif',
  custom: '"Karaoke Custom Font", system-ui, sans-serif',
} as const;
export type FontKey = keyof typeof fonts;
export const bundledFamilies: Partial<Record<FontKey, string>> = {
  nunito: 'Nunito Variable', inter: 'Inter Variable', robotoCondensed: 'Roboto Condensed Variable',
  notoSerif: 'Noto Serif Variable',
};

export function validateFontFile(name: string, bytes: ArrayBuffer) {
  if (!/\.(ttf|otf|woff2?)$/i.test(name)) throw new Error('Choose a TTF, OTF, WOFF, or WOFF2 font.');
  if (bytes.byteLength < 4 || bytes.byteLength > 32 * 1024 * 1024) throw new Error('Choose a font between 4 bytes and 32 MB.');
  const magic = new DataView(bytes).getUint32(0);
  if (![0x00010000, 0x4f54544f, 0x774f4646, 0x774f4632, 0x74727565].includes(magic)) throw new Error('This file is not a supported font.');
}

export const deviceFontNames = {
  "rounded": "Arial Rounded MT Bold",
  "sans": "Arial",
  "condensed": "Impact",
  "serif": "Georgia",
  "helveticaNeue": "Helvetica Neue",
  "avenirNext": "Avenir Next",
  "avenir": "Avenir",
  "futura": "Futura",
  "gillSans": "Gill Sans",
  "optima": "Optima",
  "palatino": "Palatino",
  "baskerville": "Baskerville",
  "hoeflerText": "Hoefler Text",
  "timesNewRoman": "Times New Roman",
  "verdana": "Verdana",
  "tahoma": "Tahoma",
  "trebuchet": "Trebuchet MS",
  "segoeUI": "Segoe UI",
  "aptos": "Aptos",
  "calibri": "Calibri",
  "cambria": "Cambria",
  "candara": "Candara",
  "consolas": "Consolas",
  "menlo": "Menlo",
  "courierNew": "Courier New",
  "roboto": "Roboto",
  "droidSans": "Droid Sans",
  "ubuntu": "Ubuntu",
  "dejavuSans": "DejaVu Sans",
  "liberationSans": "Liberation Sans",
  "pingFangSC": "PingFang SC",
  "pingFangTC": "PingFang TC",
  "hiraginoSans": "Hiragino Sans",
  "hiraginoMincho": "Hiragino Mincho ProN",
  "songtiSC": "Songti SC",
  "heitiSC": "Heiti SC",
  "microsoftYaHei": "Microsoft YaHei",
  "microsoftJhengHei": "Microsoft JhengHei",
  "simSun": "SimSun",
  "simHei": "SimHei",
  "yuGothic": "Yu Gothic",
  "yuMincho": "Yu Mincho",
  "meiryo": "Meiryo",
  "malgunGothic": "Malgun Gothic",
  "appleSDGothicNeo": "Apple SD Gothic Neo",
  "batang": "Batang"
} as const satisfies Partial<Record<FontKey, string>>;
